#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace qecgift.DB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="qec_0")]
	public partial class qecDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertt_testuser(t_testuser instance);
    partial void Updatet_testuser(t_testuser instance);
    partial void Deletet_testuser(t_testuser instance);
    partial void Insertt_vip(t_vip instance);
    partial void Updatet_vip(t_vip instance);
    partial void Deletet_vip(t_vip instance);
    partial void Insertt_giftlog(t_giftlog instance);
    partial void Updatet_giftlog(t_giftlog instance);
    partial void Deletet_giftlog(t_giftlog instance);
    #endregion
		
		public qecDataContext() : 
				base(global::qecgift.Properties.Settings.Default.qec_0ConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public qecDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public qecDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public qecDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public qecDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<t_testuser> t_testuser
		{
			get
			{
				return this.GetTable<t_testuser>();
			}
		}
		
		public System.Data.Linq.Table<t_vip> t_vip
		{
			get
			{
				return this.GetTable<t_vip>();
			}
		}
		
		public System.Data.Linq.Table<t_giftlog> t_giftlog
		{
			get
			{
				return this.GetTable<t_giftlog>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_testuser")]
	public partial class t_testuser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _user_id;
		
		private string _user_name;
		
		private int _groupid;
		
		private int _gifttimes;
		
		private string _kodname;
		
		private string _code;
		
		private System.Nullable<System.DateTime> _reg_time;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void OngroupidChanging(int value);
    partial void OngroupidChanged();
    partial void OngifttimesChanging(int value);
    partial void OngifttimesChanged();
    partial void OnkodnameChanging(string value);
    partial void OnkodnameChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void Onreg_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onreg_timeChanged();
    #endregion
		
		public t_testuser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupid", DbType="Int NOT NULL")]
		public int groupid
		{
			get
			{
				return this._groupid;
			}
			set
			{
				if ((this._groupid != value))
				{
					this.OngroupidChanging(value);
					this.SendPropertyChanging();
					this._groupid = value;
					this.SendPropertyChanged("groupid");
					this.OngroupidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gifttimes", DbType="Int NOT NULL")]
		public int gifttimes
		{
			get
			{
				return this._gifttimes;
			}
			set
			{
				if ((this._gifttimes != value))
				{
					this.OngifttimesChanging(value);
					this.SendPropertyChanging();
					this._gifttimes = value;
					this.SendPropertyChanged("gifttimes");
					this.OngifttimesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kodname", DbType="VarChar(200)")]
		public string kodname
		{
			get
			{
				return this._kodname;
			}
			set
			{
				if ((this._kodname != value))
				{
					this.OnkodnameChanging(value);
					this.SendPropertyChanging();
					this._kodname = value;
					this.SendPropertyChanged("kodname");
					this.OnkodnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="VarChar(50)")]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reg_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> reg_time
		{
			get
			{
				return this._reg_time;
			}
			set
			{
				if ((this._reg_time != value))
				{
					this.Onreg_timeChanging(value);
					this.SendPropertyChanging();
					this._reg_time = value;
					this.SendPropertyChanged("reg_time");
					this.Onreg_timeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_vip")]
	public partial class t_vip : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _vip_id;
		
		private int _topUp_num;
		
		private int _mopUp;
		
		private int _buy_main;
		
		private int _buy_gold;
		
		private int _reset_boss;
		
		private int _buy_athletics;
		
		private int _speed_onHook;
		
		private bool _unlock_boss;
		
		private int _offLine;
		
		private bool _unlock_ath_cd;
		
		private bool _unlock_skip_ath;
		
		private bool _unlock_random_gold;
		
		private int _dispatch_time_reduction;
		
		private bool _accelerate_dispatch;
		
		private bool _boss_gold;
		
		private int _random_event_sum;
		
		private int _dispatch_gold_add;
		
		private int _event_refresh;
		
		private int _dispatch_meanwhile_num;
		
		private bool _unlock_finish_dispatch;
		
		private bool _unlock_finish_all_random;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onvip_idChanging(int value);
    partial void Onvip_idChanged();
    partial void OntopUp_numChanging(int value);
    partial void OntopUp_numChanged();
    partial void OnmopUpChanging(int value);
    partial void OnmopUpChanged();
    partial void Onbuy_mainChanging(int value);
    partial void Onbuy_mainChanged();
    partial void Onbuy_goldChanging(int value);
    partial void Onbuy_goldChanged();
    partial void Onreset_bossChanging(int value);
    partial void Onreset_bossChanged();
    partial void Onbuy_athleticsChanging(int value);
    partial void Onbuy_athleticsChanged();
    partial void Onspeed_onHookChanging(int value);
    partial void Onspeed_onHookChanged();
    partial void Onunlock_bossChanging(bool value);
    partial void Onunlock_bossChanged();
    partial void OnoffLineChanging(int value);
    partial void OnoffLineChanged();
    partial void Onunlock_ath_cdChanging(bool value);
    partial void Onunlock_ath_cdChanged();
    partial void Onunlock_skip_athChanging(bool value);
    partial void Onunlock_skip_athChanged();
    partial void Onunlock_random_goldChanging(bool value);
    partial void Onunlock_random_goldChanged();
    partial void Ondispatch_time_reductionChanging(int value);
    partial void Ondispatch_time_reductionChanged();
    partial void Onaccelerate_dispatchChanging(bool value);
    partial void Onaccelerate_dispatchChanged();
    partial void Onboss_goldChanging(bool value);
    partial void Onboss_goldChanged();
    partial void Onrandom_event_sumChanging(int value);
    partial void Onrandom_event_sumChanged();
    partial void Ondispatch_gold_addChanging(int value);
    partial void Ondispatch_gold_addChanged();
    partial void Onevent_refreshChanging(int value);
    partial void Onevent_refreshChanged();
    partial void Ondispatch_meanwhile_numChanging(int value);
    partial void Ondispatch_meanwhile_numChanged();
    partial void Onunlock_finish_dispatchChanging(bool value);
    partial void Onunlock_finish_dispatchChanged();
    partial void Onunlock_finish_all_randomChanging(bool value);
    partial void Onunlock_finish_all_randomChanged();
    #endregion
		
		public t_vip()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vip_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int vip_id
		{
			get
			{
				return this._vip_id;
			}
			set
			{
				if ((this._vip_id != value))
				{
					this.Onvip_idChanging(value);
					this.SendPropertyChanging();
					this._vip_id = value;
					this.SendPropertyChanged("vip_id");
					this.Onvip_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_topUp_num", DbType="Int NOT NULL")]
		public int topUp_num
		{
			get
			{
				return this._topUp_num;
			}
			set
			{
				if ((this._topUp_num != value))
				{
					this.OntopUp_numChanging(value);
					this.SendPropertyChanging();
					this._topUp_num = value;
					this.SendPropertyChanged("topUp_num");
					this.OntopUp_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mopUp", DbType="Int NOT NULL")]
		public int mopUp
		{
			get
			{
				return this._mopUp;
			}
			set
			{
				if ((this._mopUp != value))
				{
					this.OnmopUpChanging(value);
					this.SendPropertyChanging();
					this._mopUp = value;
					this.SendPropertyChanged("mopUp");
					this.OnmopUpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_buy_main", DbType="Int NOT NULL")]
		public int buy_main
		{
			get
			{
				return this._buy_main;
			}
			set
			{
				if ((this._buy_main != value))
				{
					this.Onbuy_mainChanging(value);
					this.SendPropertyChanging();
					this._buy_main = value;
					this.SendPropertyChanged("buy_main");
					this.Onbuy_mainChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_buy_gold", DbType="Int NOT NULL")]
		public int buy_gold
		{
			get
			{
				return this._buy_gold;
			}
			set
			{
				if ((this._buy_gold != value))
				{
					this.Onbuy_goldChanging(value);
					this.SendPropertyChanging();
					this._buy_gold = value;
					this.SendPropertyChanged("buy_gold");
					this.Onbuy_goldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reset_boss", DbType="Int NOT NULL")]
		public int reset_boss
		{
			get
			{
				return this._reset_boss;
			}
			set
			{
				if ((this._reset_boss != value))
				{
					this.Onreset_bossChanging(value);
					this.SendPropertyChanging();
					this._reset_boss = value;
					this.SendPropertyChanged("reset_boss");
					this.Onreset_bossChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_buy_athletics", DbType="Int NOT NULL")]
		public int buy_athletics
		{
			get
			{
				return this._buy_athletics;
			}
			set
			{
				if ((this._buy_athletics != value))
				{
					this.Onbuy_athleticsChanging(value);
					this.SendPropertyChanging();
					this._buy_athletics = value;
					this.SendPropertyChanged("buy_athletics");
					this.Onbuy_athleticsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_speed_onHook", DbType="Int NOT NULL")]
		public int speed_onHook
		{
			get
			{
				return this._speed_onHook;
			}
			set
			{
				if ((this._speed_onHook != value))
				{
					this.Onspeed_onHookChanging(value);
					this.SendPropertyChanging();
					this._speed_onHook = value;
					this.SendPropertyChanged("speed_onHook");
					this.Onspeed_onHookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unlock_boss", DbType="Bit NOT NULL")]
		public bool unlock_boss
		{
			get
			{
				return this._unlock_boss;
			}
			set
			{
				if ((this._unlock_boss != value))
				{
					this.Onunlock_bossChanging(value);
					this.SendPropertyChanging();
					this._unlock_boss = value;
					this.SendPropertyChanged("unlock_boss");
					this.Onunlock_bossChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_offLine", DbType="Int NOT NULL")]
		public int offLine
		{
			get
			{
				return this._offLine;
			}
			set
			{
				if ((this._offLine != value))
				{
					this.OnoffLineChanging(value);
					this.SendPropertyChanging();
					this._offLine = value;
					this.SendPropertyChanged("offLine");
					this.OnoffLineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unlock_ath_cd", DbType="Bit NOT NULL")]
		public bool unlock_ath_cd
		{
			get
			{
				return this._unlock_ath_cd;
			}
			set
			{
				if ((this._unlock_ath_cd != value))
				{
					this.Onunlock_ath_cdChanging(value);
					this.SendPropertyChanging();
					this._unlock_ath_cd = value;
					this.SendPropertyChanged("unlock_ath_cd");
					this.Onunlock_ath_cdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unlock_skip_ath", DbType="Bit NOT NULL")]
		public bool unlock_skip_ath
		{
			get
			{
				return this._unlock_skip_ath;
			}
			set
			{
				if ((this._unlock_skip_ath != value))
				{
					this.Onunlock_skip_athChanging(value);
					this.SendPropertyChanging();
					this._unlock_skip_ath = value;
					this.SendPropertyChanged("unlock_skip_ath");
					this.Onunlock_skip_athChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unlock_random_gold", DbType="Bit NOT NULL")]
		public bool unlock_random_gold
		{
			get
			{
				return this._unlock_random_gold;
			}
			set
			{
				if ((this._unlock_random_gold != value))
				{
					this.Onunlock_random_goldChanging(value);
					this.SendPropertyChanging();
					this._unlock_random_gold = value;
					this.SendPropertyChanged("unlock_random_gold");
					this.Onunlock_random_goldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dispatch_time_reduction", DbType="Int NOT NULL")]
		public int dispatch_time_reduction
		{
			get
			{
				return this._dispatch_time_reduction;
			}
			set
			{
				if ((this._dispatch_time_reduction != value))
				{
					this.Ondispatch_time_reductionChanging(value);
					this.SendPropertyChanging();
					this._dispatch_time_reduction = value;
					this.SendPropertyChanged("dispatch_time_reduction");
					this.Ondispatch_time_reductionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accelerate_dispatch", DbType="Bit NOT NULL")]
		public bool accelerate_dispatch
		{
			get
			{
				return this._accelerate_dispatch;
			}
			set
			{
				if ((this._accelerate_dispatch != value))
				{
					this.Onaccelerate_dispatchChanging(value);
					this.SendPropertyChanging();
					this._accelerate_dispatch = value;
					this.SendPropertyChanged("accelerate_dispatch");
					this.Onaccelerate_dispatchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_boss_gold", DbType="Bit NOT NULL")]
		public bool boss_gold
		{
			get
			{
				return this._boss_gold;
			}
			set
			{
				if ((this._boss_gold != value))
				{
					this.Onboss_goldChanging(value);
					this.SendPropertyChanging();
					this._boss_gold = value;
					this.SendPropertyChanged("boss_gold");
					this.Onboss_goldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_random_event_sum", DbType="Int NOT NULL")]
		public int random_event_sum
		{
			get
			{
				return this._random_event_sum;
			}
			set
			{
				if ((this._random_event_sum != value))
				{
					this.Onrandom_event_sumChanging(value);
					this.SendPropertyChanging();
					this._random_event_sum = value;
					this.SendPropertyChanged("random_event_sum");
					this.Onrandom_event_sumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dispatch_gold_add", DbType="Int NOT NULL")]
		public int dispatch_gold_add
		{
			get
			{
				return this._dispatch_gold_add;
			}
			set
			{
				if ((this._dispatch_gold_add != value))
				{
					this.Ondispatch_gold_addChanging(value);
					this.SendPropertyChanging();
					this._dispatch_gold_add = value;
					this.SendPropertyChanged("dispatch_gold_add");
					this.Ondispatch_gold_addChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_event_refresh", DbType="Int NOT NULL")]
		public int event_refresh
		{
			get
			{
				return this._event_refresh;
			}
			set
			{
				if ((this._event_refresh != value))
				{
					this.Onevent_refreshChanging(value);
					this.SendPropertyChanging();
					this._event_refresh = value;
					this.SendPropertyChanged("event_refresh");
					this.Onevent_refreshChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dispatch_meanwhile_num", DbType="Int NOT NULL")]
		public int dispatch_meanwhile_num
		{
			get
			{
				return this._dispatch_meanwhile_num;
			}
			set
			{
				if ((this._dispatch_meanwhile_num != value))
				{
					this.Ondispatch_meanwhile_numChanging(value);
					this.SendPropertyChanging();
					this._dispatch_meanwhile_num = value;
					this.SendPropertyChanged("dispatch_meanwhile_num");
					this.Ondispatch_meanwhile_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unlock_finish_dispatch", DbType="Bit NOT NULL")]
		public bool unlock_finish_dispatch
		{
			get
			{
				return this._unlock_finish_dispatch;
			}
			set
			{
				if ((this._unlock_finish_dispatch != value))
				{
					this.Onunlock_finish_dispatchChanging(value);
					this.SendPropertyChanging();
					this._unlock_finish_dispatch = value;
					this.SendPropertyChanged("unlock_finish_dispatch");
					this.Onunlock_finish_dispatchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unlock_finish_all_random", DbType="Bit NOT NULL")]
		public bool unlock_finish_all_random
		{
			get
			{
				return this._unlock_finish_all_random;
			}
			set
			{
				if ((this._unlock_finish_all_random != value))
				{
					this.Onunlock_finish_all_randomChanging(value);
					this.SendPropertyChanging();
					this._unlock_finish_all_random = value;
					this.SendPropertyChanged("unlock_finish_all_random");
					this.Onunlock_finish_all_randomChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_giftlog")]
	public partial class t_giftlog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _user_id;
		
		private System.Nullable<int> _addgem;
		
		private System.DateTime _addtime;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void OnaddgemChanging(System.Nullable<int> value);
    partial void OnaddgemChanged();
    partial void OnaddtimeChanging(System.DateTime value);
    partial void OnaddtimeChanged();
    #endregion
		
		public t_giftlog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int NOT NULL")]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_addgem", DbType="Int")]
		public System.Nullable<int> addgem
		{
			get
			{
				return this._addgem;
			}
			set
			{
				if ((this._addgem != value))
				{
					this.OnaddgemChanging(value);
					this.SendPropertyChanging();
					this._addgem = value;
					this.SendPropertyChanged("addgem");
					this.OnaddgemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_addtime", DbType="DateTime NOT NULL")]
		public System.DateTime addtime
		{
			get
			{
				return this._addtime;
			}
			set
			{
				if ((this._addtime != value))
				{
					this.OnaddtimeChanging(value);
					this.SendPropertyChanging();
					this._addtime = value;
					this.SendPropertyChanged("addtime");
					this.OnaddtimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
