#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace qecgift.DB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="qec_1")]
	public partial class qec1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertt_user_info(t_user_info instance);
    partial void Updatet_user_info(t_user_info instance);
    partial void Deletet_user_info(t_user_info instance);
    #endregion
		
		public qec1DataContext() : 
				base(global::qecgift.Properties.Settings.Default.qec_1ConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public qec1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public qec1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public qec1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public qec1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<t_user_info> t_user_info
		{
			get
			{
				return this.GetTable<t_user_info>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_user_info")]
	public partial class t_user_info : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _user_id;
		
		private string _user_nickname;
		
		private int _curr_map;
		
		private int _user_level;
		
		private int _hit_rate;
		
		private int _crit_rate;
		
		private System.DateTime _create_time;
		
		private System.DateTime _last_enter;
		
		private System.DateTime _last_req;
		
		private System.Nullable<System.DateTime> _arrive_level;
		
		private decimal _user_exp;
		
		private decimal _user_gem;
		
		private decimal _user_gold;
		
		private int _evade_rate;
		
		private int _fight;
		
		private int _main;
		
		private int _knapsac_num;
		
		private string _head_pic;
		
		private decimal _card_exp;
		
		private int _vip;
		
		private int _topup_num;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void Onuser_nicknameChanging(string value);
    partial void Onuser_nicknameChanged();
    partial void Oncurr_mapChanging(int value);
    partial void Oncurr_mapChanged();
    partial void Onuser_levelChanging(int value);
    partial void Onuser_levelChanged();
    partial void Onhit_rateChanging(int value);
    partial void Onhit_rateChanged();
    partial void Oncrit_rateChanging(int value);
    partial void Oncrit_rateChanged();
    partial void Oncreate_timeChanging(System.DateTime value);
    partial void Oncreate_timeChanged();
    partial void Onlast_enterChanging(System.DateTime value);
    partial void Onlast_enterChanged();
    partial void Onlast_reqChanging(System.DateTime value);
    partial void Onlast_reqChanged();
    partial void Onarrive_levelChanging(System.Nullable<System.DateTime> value);
    partial void Onarrive_levelChanged();
    partial void Onuser_expChanging(decimal value);
    partial void Onuser_expChanged();
    partial void Onuser_gemChanging(decimal value);
    partial void Onuser_gemChanged();
    partial void Onuser_goldChanging(decimal value);
    partial void Onuser_goldChanged();
    partial void Onevade_rateChanging(int value);
    partial void Onevade_rateChanged();
    partial void OnfightChanging(int value);
    partial void OnfightChanged();
    partial void OnmainChanging(int value);
    partial void OnmainChanged();
    partial void Onknapsac_numChanging(int value);
    partial void Onknapsac_numChanged();
    partial void Onhead_picChanging(string value);
    partial void Onhead_picChanged();
    partial void Oncard_expChanging(decimal value);
    partial void Oncard_expChanged();
    partial void OnvipChanging(int value);
    partial void OnvipChanged();
    partial void Ontopup_numChanging(int value);
    partial void Ontopup_numChanged();
    #endregion
		
		public t_user_info()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_nickname", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string user_nickname
		{
			get
			{
				return this._user_nickname;
			}
			set
			{
				if ((this._user_nickname != value))
				{
					this.Onuser_nicknameChanging(value);
					this.SendPropertyChanging();
					this._user_nickname = value;
					this.SendPropertyChanged("user_nickname");
					this.Onuser_nicknameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_curr_map", DbType="Int NOT NULL")]
		public int curr_map
		{
			get
			{
				return this._curr_map;
			}
			set
			{
				if ((this._curr_map != value))
				{
					this.Oncurr_mapChanging(value);
					this.SendPropertyChanging();
					this._curr_map = value;
					this.SendPropertyChanged("curr_map");
					this.Oncurr_mapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_level", DbType="Int NOT NULL")]
		public int user_level
		{
			get
			{
				return this._user_level;
			}
			set
			{
				if ((this._user_level != value))
				{
					this.Onuser_levelChanging(value);
					this.SendPropertyChanging();
					this._user_level = value;
					this.SendPropertyChanged("user_level");
					this.Onuser_levelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hit_rate", DbType="Int NOT NULL")]
		public int hit_rate
		{
			get
			{
				return this._hit_rate;
			}
			set
			{
				if ((this._hit_rate != value))
				{
					this.Onhit_rateChanging(value);
					this.SendPropertyChanging();
					this._hit_rate = value;
					this.SendPropertyChanged("hit_rate");
					this.Onhit_rateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_crit_rate", DbType="Int NOT NULL")]
		public int crit_rate
		{
			get
			{
				return this._crit_rate;
			}
			set
			{
				if ((this._crit_rate != value))
				{
					this.Oncrit_rateChanging(value);
					this.SendPropertyChanging();
					this._crit_rate = value;
					this.SendPropertyChanged("crit_rate");
					this.Oncrit_rateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_time", DbType="DateTime NOT NULL")]
		public System.DateTime create_time
		{
			get
			{
				return this._create_time;
			}
			set
			{
				if ((this._create_time != value))
				{
					this.Oncreate_timeChanging(value);
					this.SendPropertyChanging();
					this._create_time = value;
					this.SendPropertyChanged("create_time");
					this.Oncreate_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_enter", DbType="DateTime NOT NULL")]
		public System.DateTime last_enter
		{
			get
			{
				return this._last_enter;
			}
			set
			{
				if ((this._last_enter != value))
				{
					this.Onlast_enterChanging(value);
					this.SendPropertyChanging();
					this._last_enter = value;
					this.SendPropertyChanged("last_enter");
					this.Onlast_enterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_req", DbType="DateTime NOT NULL")]
		public System.DateTime last_req
		{
			get
			{
				return this._last_req;
			}
			set
			{
				if ((this._last_req != value))
				{
					this.Onlast_reqChanging(value);
					this.SendPropertyChanging();
					this._last_req = value;
					this.SendPropertyChanged("last_req");
					this.Onlast_reqChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_arrive_level", DbType="DateTime")]
		public System.Nullable<System.DateTime> arrive_level
		{
			get
			{
				return this._arrive_level;
			}
			set
			{
				if ((this._arrive_level != value))
				{
					this.Onarrive_levelChanging(value);
					this.SendPropertyChanging();
					this._arrive_level = value;
					this.SendPropertyChanged("arrive_level");
					this.Onarrive_levelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_exp", DbType="Decimal(18,0) NOT NULL")]
		public decimal user_exp
		{
			get
			{
				return this._user_exp;
			}
			set
			{
				if ((this._user_exp != value))
				{
					this.Onuser_expChanging(value);
					this.SendPropertyChanging();
					this._user_exp = value;
					this.SendPropertyChanged("user_exp");
					this.Onuser_expChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_gem", DbType="Decimal(18,0) NOT NULL")]
		public decimal user_gem
		{
			get
			{
				return this._user_gem;
			}
			set
			{
				if ((this._user_gem != value))
				{
					this.Onuser_gemChanging(value);
					this.SendPropertyChanging();
					this._user_gem = value;
					this.SendPropertyChanged("user_gem");
					this.Onuser_gemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_gold", DbType="Decimal(18,0) NOT NULL")]
		public decimal user_gold
		{
			get
			{
				return this._user_gold;
			}
			set
			{
				if ((this._user_gold != value))
				{
					this.Onuser_goldChanging(value);
					this.SendPropertyChanging();
					this._user_gold = value;
					this.SendPropertyChanged("user_gold");
					this.Onuser_goldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_evade_rate", DbType="Int NOT NULL")]
		public int evade_rate
		{
			get
			{
				return this._evade_rate;
			}
			set
			{
				if ((this._evade_rate != value))
				{
					this.Onevade_rateChanging(value);
					this.SendPropertyChanging();
					this._evade_rate = value;
					this.SendPropertyChanged("evade_rate");
					this.Onevade_rateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fight", DbType="Int NOT NULL")]
		public int fight
		{
			get
			{
				return this._fight;
			}
			set
			{
				if ((this._fight != value))
				{
					this.OnfightChanging(value);
					this.SendPropertyChanging();
					this._fight = value;
					this.SendPropertyChanged("fight");
					this.OnfightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_main", DbType="Int NOT NULL")]
		public int main
		{
			get
			{
				return this._main;
			}
			set
			{
				if ((this._main != value))
				{
					this.OnmainChanging(value);
					this.SendPropertyChanging();
					this._main = value;
					this.SendPropertyChanged("main");
					this.OnmainChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_knapsac_num", DbType="Int NOT NULL")]
		public int knapsac_num
		{
			get
			{
				return this._knapsac_num;
			}
			set
			{
				if ((this._knapsac_num != value))
				{
					this.Onknapsac_numChanging(value);
					this.SendPropertyChanging();
					this._knapsac_num = value;
					this.SendPropertyChanged("knapsac_num");
					this.Onknapsac_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_head_pic", DbType="VarChar(50)")]
		public string head_pic
		{
			get
			{
				return this._head_pic;
			}
			set
			{
				if ((this._head_pic != value))
				{
					this.Onhead_picChanging(value);
					this.SendPropertyChanging();
					this._head_pic = value;
					this.SendPropertyChanged("head_pic");
					this.Onhead_picChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_card_exp", DbType="Decimal(18,0) NOT NULL")]
		public decimal card_exp
		{
			get
			{
				return this._card_exp;
			}
			set
			{
				if ((this._card_exp != value))
				{
					this.Oncard_expChanging(value);
					this.SendPropertyChanging();
					this._card_exp = value;
					this.SendPropertyChanged("card_exp");
					this.Oncard_expChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vip", DbType="Int NOT NULL")]
		public int vip
		{
			get
			{
				return this._vip;
			}
			set
			{
				if ((this._vip != value))
				{
					this.OnvipChanging(value);
					this.SendPropertyChanging();
					this._vip = value;
					this.SendPropertyChanged("vip");
					this.OnvipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_topup_num", DbType="Int NOT NULL")]
		public int topup_num
		{
			get
			{
				return this._topup_num;
			}
			set
			{
				if ((this._topup_num != value))
				{
					this.Ontopup_numChanging(value);
					this.SendPropertyChanging();
					this._topup_num = value;
					this.SendPropertyChanged("topup_num");
					this.Ontopup_numChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
